export const GET_SHOP_REQUEST = 'GET_SHOP_REQUEST';
export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAILURE = 'GET_SHOP_FAILURE';

export const ADD_SHOP_REQUEST = 'ADD_SHOP_REQUEST';
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS';
export const ADD_SHOP_FAILURE = 'ADD_SHOP_FAILURE';